### ISSUE TITLE
update info while drawing

### ISSUE THREAD

**Issue by pere** [mapbox/mapbox-gl-draw#1003]
There is a chance to get info when user is drawing a polygon? (ex: area). 

I can calculate the area when user has finished drawing, because there is an event detecting it (draw.created), but no event for 'creating polygon' as the user draws.

I am trying to do something like this (Leafletjs).Thanks

https://jsfiddle.net/user2314737/Lscupxqp/

**Comment by nzjs** [comment]
Hi, this is not a complete solution for the jsfiddle demo, but this is what I came up with to display a drawing indicator to the user. I'm sure you could customise it easy enough to clone the Leaflet functionality

1. Create a new Drawing Active control:
```js
class DrawingActiveControl {
  onAdd(map) {
    var indicator = document.getElementsByClassName('drawing-active-control')
    if (indicator.length === 0) {
      this.map = map;
      this.container = document.createElement('div');
      this.container.className = 'drawing-active-control';
      this.container.innerHTML = '<strong>Drawing Tool Active</strong><br/>' +
        '<small>(Hit Enter or double-click to finish)</small>';
      return this.container;
    }
  }

  onRemove() {
    try {
      this.container.parentNode.removeChild(this.container);
      this.map = undefined;
    }
    catch (e) { }
  }
}
```

2. Create a function that manages the control (**draw** is your main drawing control):
```js
  drawingActive = new DrawingActiveControl();

  showHideDrawingIndicator() {
    if (draw.getMode() === 'draw_line_string' || draw.getMode() === 'draw_polygon') {
      map.addControl(drawingActive, 'top-left');
    }
    else if (draw.getMode() === 'simple_select') {
      map.removeControl(drawingActive);
    }
  }
```

3. Display or hide the indicator control if user is currently drawing:
```js
  map.on('draw.modechange', function (e) {
    showHideDrawingIndicator();
  });
```

4. Style the control however you want. this is mine:
```css
.drawing-active-control {
    padding: 10px;
    font-size: 20px;
    font-weight: 500;
    line-height: 26px;
    text-align: center;
    font-family: "Open Sans", "Helvetica Neue", Arial, Helvetica, sans-serif;
    position: absolute;
    top: 60px;
    left: 30vw;
    background-color: #fff;
    opacity: 0.8;
    min-width: 300px;
    max-width: 500px;
    z-index: 1;
    border-radius: 4px;
}
```
![control](https://user-images.githubusercontent.com/5310559/91670930-1b9a8080-eb76-11ea-87f6-a68ba61da848.png)
